Build script readiness for renaming cgcs-centos-repo to centos-repo
I want the build to work with either centos-repo or cgcs-centos-repo.
In many places we will be testing for the existance centos-repo as
the prefered path, then fall back to cgcs-centos-repo as an alternative.
If neither are present, either exit or continue but assuming the new
path is intended.

NOTE: The patch_rebase_1/2/3/4 scripts remain broken, but I hope
to salvage them one day.  The current coding assumes content under
centos-repo/cgcs-centos-repo is managed by a git, which is not
currently true.

Story: 2006387
Task: 36912
Change-Id: I8f694814c41957c5b37eb2e64b653b7d42f2e2c9
Signed-off-by: Scott Little <scott.little@windriver.com>

diff --git a/build-tools/build-pkgs-serial b/build-tools/build-pkgs-serial
--- a/build-tools/build-pkgs-serial
+++ b/build-tools/build-pkgs-serial
@@ -65,6 +65,15 @@ DEP_TEST_FLAG=0
 
 export BUILD_AVOIDANCE_URL=""
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
 
 # read the options
 TEMP=$(getopt -o h --long serial,rt,std,installer,containers,layer:,edit,build-avoidance,no-build-avoidance,build-avoidance-dir:,build-avoidance-host:,build-avoidance-user:,build-avoidance-day:,no-meta-patch,no-descendants,no-required,no-build-info,no-autoclean,formal,careful,help,clean,dep-test,append-log -n 'build-pkgs-serial' -- "$@")
@@ -194,7 +203,12 @@ find_targets () {
          for d2 in $(grep -v '^#' $d/$centos_pkg_dirs); do
             name=""
             if [ -f $d/$d2/centos/srpm_path ]; then
-                path=$(cat $d/$d2/centos/srpm_path | head -n 1 | sed "s#^mirror:CentOS/tis-r3-CentOS/mitaka#$MY_REPO/cgcs-centos-repo#" | sed "s#^mirror:#$MY_REPO/cgcs-centos-repo/#" | sed "s#^repo:#$MY_REPO/#" | sed "s#^3rd_party:#$MY_REPO/cgcs-3rd-party-repo/#" | sed "s#^Source/#$MY_REPO/cgcs-centos-repo/Source/#")
+               path=$(cat $d/$d2/centos/srpm_path | head -n 1 | \
+                      sed -e "s#^mirror:CentOS/tis-r3-CentOS/mitaka#${CENTOS_REPO}#" \
+                          -e "s#^mirror:#${CENTOS_REPO}/#" \
+                          -e "s#^repo:#$MY_REPO/#" \
+                          -e "s#^3rd_party:#$MY_REPO/cgcs-3rd-party-repo/#" \
+                          -e "s#^Source/#${CENTOS_REPO}/Source/#")
                 name=$(rpm -q --qf='%{NAME}' --nosignature -p $path)
             else
                 path=$(find $d/$d2/centos/ -name '*.spec' | head -n 1)
diff --git a/build-tools/modify-build-cfg b/build-tools/modify-build-cfg
--- a/build-tools/modify-build-cfg
+++ b/build-tools/modify-build-cfg
@@ -13,12 +13,22 @@
 
 LAYER=${2:-$LAYER}
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
+
 # Try to find a layer specific mock.cfg.proto
-MOCK_CFG_PROTO="$MY_REPO/cgcs-centos-repo/mock.cfg.${LAYER}.proto"
+MOCK_CFG_PROTO="${CENTOS_REPO}/mock.cfg.${LAYER}.proto"
 echo "==== Try MOCK_CFG_PROTO=$MOCK_CFG_PROTO ===="
 if [ ! -f "$MOCK_CFG_PROTO" ]; then
     # Not present, Use default mock.cfg.proto
-    MOCK_CFG_PROTO="$MY_REPO/cgcs-centos-repo/mock.cfg.proto"
+    MOCK_CFG_PROTO="${CENTOS_REPO}/mock.cfg.proto"
 fi
 
 echo "==== Use MOCK_CFG_PROTO=$MOCK_CFG_PROTO ===="
diff --git a/build-tools/patch_rebase_2 b/build-tools/patch_rebase_2
--- a/build-tools/patch_rebase_2
+++ b/build-tools/patch_rebase_2
@@ -4,6 +4,16 @@
 # Update srpm_path for packages to be upgraded
 #
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
+
 usage () {
     echo ""
     echo "Step 2: Update srpm_path for packages to be upgraded"
@@ -11,7 +21,7 @@ usage () {
     echo "Usage: "
     echo "   patch_rebase_2 [--origin_branch <branch>] [--working_branch <branch>] [--upversion_data <file>]"
     echo ""
-    echo "Assumes cgcs-centos-repo already has a working_branch commit that sets the new symlinks."
+    echo "Assumes $(basename ${CENTOS_REPO}) already has a working_branch commit that sets the new symlinks."
     echo ""
     echo "The upversion_data file has data on all the src.rpm being updated in the format:"
     echo "  export UPVERSION_DATA=$MY_WORKSPACE/upversion.log"
diff --git a/build-tools/patch_rebase_4 b/build-tools/patch_rebase_4
--- a/build-tools/patch_rebase_4
+++ b/build-tools/patch_rebase_4
@@ -4,6 +4,16 @@
 # Migrate Titanium Cloud patches to the new package version
 #
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
+
 usage () {
     echo ""
     echo "Step 4: Migrate Titanium Cloud patches to the new package version"
@@ -11,7 +21,7 @@ usage () {
     echo "Usage: "
     echo "   patch_rebase_4 [--origin_branch <branch>] [--working_branch <branch>] [--upversion_data <file>]"
     echo ""
-    echo "Assumes cgcs-centos-repo already has a working_branch commit that sets the new symlinks."
+    echo "Assumes $(basename ${CENTOS_REPO}) already has a working_branch commit that sets the new symlinks."
     echo ""
     echo "The upversion_data file has data on all the src.rpm being updated in the format:"
     echo "  export UPVERSION_DATA=$MY_WORKSPACE/upversion.log"
@@ -92,10 +102,10 @@ if [ "$DISPLAY" == "" ]; then
 fi
 
 # One step back to see the old symlinks
-cd $MY_REPO/cgcs-centos-repo
+cd ${CENTOS_REPO}
 git checkout $WORKING_BRANCH
 if [ $? != 0 ]; then
-   echo "ERROR: Can't checkout branch '$WORKING_BRANCH' in directory '$MY_REPO/cgcs-centos-repo'"
+   echo "ERROR: Can't checkout branch '$WORKING_BRANCH' in directory '${CENTOS_REPO}'"
    exit 1
 fi
 
diff --git a/build-tools/update-efiboot-image b/build-tools/update-efiboot-image
--- a/build-tools/update-efiboot-image
+++ b/build-tools/update-efiboot-image
@@ -133,23 +133,33 @@ fi
 # Update the vanilla UEFI Centos grub.cfg with the Titanium Cloud version
 ${SUDOPREFIX} cp "$BSP_FILES_PATH/grub.cfg"  "$EFI_MOUNT/EFI/BOOT/grub.cfg"
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
+
 # Update the grub and shim executables with the Titanium Cloud signed versions
 #
 # To do this, we extract the RPMS, grab the two executables we need, and replace
 # the ones in the current filesystem
 TMPDIR=`mktemp -d`
-SHIMPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS $MY_REPO/cgcs-centos-repo/Binary -name 'shim-x64-[0-9]*.x86_64.rpm'`
+SHIMPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS ${CENTOS_REPO}/Binary -name 'shim-x64-[0-9]*.x86_64.rpm'`
 if [ -z "$SHIMPKG" ]; then
-    SHIMPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS $MY_REPO/cgcs-centos-repo/Binary -name 'shim-[0-9]*.x86_64.rpm'`
+    SHIMPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS ${CENTOS_REPO}/Binary -name 'shim-[0-9]*.x86_64.rpm'`
 fi
 if [ -z "$SHIMPKG" ]; then
     printf "  Error -- could not locate shim binary package"
     exit 1
 fi
 
-GRUBPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS $MY_REPO/cgcs-centos-repo/Binary -name 'grub2-efi-x64-[0-9]*.x86_64.rpm'`
+GRUBPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS ${CENTOS_REPO}/Binary -name 'grub2-efi-x64-[0-9]*.x86_64.rpm'`
 if [ -z "$GRUBPKG" ]; then
-    GRUBPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS $MY_REPO/cgcs-centos-repo/Binary -name 'grub2-efi-[0-9]*.x86_64.rpm'`
+    GRUBPKG=`find $MY_WORKSPACE/std/rpmbuild/RPMS ${CENTOS_REPO}/Binary -name 'grub2-efi-[0-9]*.x86_64.rpm'`
 fi
 if [ -z "$GRUBPKG" ]; then
     printf "  Error -- could not locate grub binary package"
diff --git a/build-tools/update-pxe-network-installer b/build-tools/update-pxe-network-installer
--- a/build-tools/update-pxe-network-installer
+++ b/build-tools/update-pxe-network-installer
@@ -3,6 +3,16 @@
 ## based on RPMs generated by "build-pkgs" and "build-iso"
 ## created by Yong Hu (yong.hu@intel.com), 05/24/2018
 
+# For backward compatibility.  Old repo location or new?
+CENTOS_REPO=${MY_REPO}/centos-repo
+if [ ! -d ${CENTOS_REPO} ]; then
+    CENTOS_REPO=${MY_REPO}/cgcs-centos-repo
+    if [ ! -d ${CENTOS_REPO} ]; then
+        echo "ERROR: directory ${MY_REPO}/centos-repo not found."
+        exit 1
+    fi
+fi
+
 find_and_copy_rpm () {
     local name="${1}"
     local pattern="${2}"
@@ -13,9 +23,9 @@ find_and_copy_rpm () {
     found=$(find $MY_BUILD_DIR/${build_type}/rpmbuild/RPMS -type f -name "${pattern}" | head -n 1)
     if [ ! -n "${found}" ];then
         if [ "${build_type}" != "rt" ]; then
-            found=$(find $MY_REPO/cgcs-centos-repo/Binary -type l -name "${pattern}" | head -n 1)
+            found=$(find ${CENTOS_REPO}/Binary -type l -name "${pattern}" | head -n 1)
         else
-            found=$(find $MY_REPO/cgcs-centos-repo/${build_type}/Binary -type l -name "${pattern}" | head -n 1)
+            found=$(find ${CENTOS_REPO}/${build_type}/Binary -type l -name "${pattern}" | head -n 1)
         fi
     fi
 
@@ -40,13 +50,12 @@ fi
 cd $pxe_network_installer_dir
 
 echo "step 1: copy original images: vmlinuz, initrd.img, squashfs.img"
-CENTOS_REPO="cgcs-centos-repo"
 orig_img_dir="orig"
 if [ ! -d $orig_img_dir ];then
     mkdir -p $orig_img_dir
 fi
 
-orig_initrd_img="$MY_REPO/$CENTOS_REPO/Binary/images/pxeboot/initrd.img"
+orig_initrd_img="${CENTOS_REPO}/Binary/images/pxeboot/initrd.img"
 if [ -f $orig_initrd_img ]; then
     cp -f $orig_initrd_img $pxe_network_installer_dir/$orig_img_dir/.
 else
@@ -54,7 +63,7 @@ else
     exit -1
 fi
 
-orig_squashfs_img="$MY_REPO/$CENTOS_REPO/Binary/LiveOS/squashfs.img"
+orig_squashfs_img="$i{CENTOS_REPO}/Binary/LiveOS/squashfs.img"
 if [ -f $orig_squashfs_img ]; then
     cp -f $orig_squashfs_img $pxe_network_installer_dir/$orig_img_dir/.
 else
