sign-secure-boot: discern bullseye/trixie paths
Fix the path to base-bullseye.yaml or similar to include the os
codename (bullseye/trixie).

TESTS
=====================
* Rebuild builder container
* Make sure DEBIAN_DISTRIBUTION is set to "bullseye"

Signed-off-by: Davlet Panech <davlet.panech@windriver.com>
Change-Id: I9dd8b63b58a2853677f794a2728f990587888448

diff --git a/build-tools/sign-secure-boot_debian b/build-tools/sign-secure-boot_debian
--- a/build-tools/sign-secure-boot_debian
+++ b/build-tools/sign-secure-boot_debian
@@ -40,6 +40,11 @@ if [ -z "${SIGNING_KEY_NAME}" ]; then
     echo "Warning: SIGNING_KEY_NAME no set in your environment, using '${SIGNING_KEY_NAME}'"
 fi
 
+if [ -z "${DEBIAN_DISTRIBUTION}" ]; then
+    echo "ERROR: Please set DEBIAN_DISTRIBUTION first!"
+    exit 1
+fi
+
 # Get shim deb version number.
 SHIM_DEB=$(ls ${MY_WORKSPACE}/std/shim/shim-unsigned_*_amd64.deb)
 SHIM_DEB=${SHIM_DEB##*/}
@@ -156,7 +161,7 @@ echo "***Finish signing grub***"
 
 echo "***(3) Prepare gpg signing for lat genimage***"
 # The gpg signings are done when build-image. Here prepare the setting file for lat.
-YAML_FILE=${MY_REPO_ROOT_DIR}/stx-tools/debian-mirror-tools/config/debian/common/base-bullseye.yaml
+YAML_FILE=${MY_REPO_ROOT_DIR}/stx-tools/debian-mirror-tools/config/debian/${DEBIAN_DISTRIBUTION}/common/base-${DEBIAN_DISTRIBUTION}.yaml
 # Definition for signing part of rootfs-post-scripts, which is used to sign kernel std/rt images and LockDown.efi.
 ROOTFS_SIGNING_FILE=${MY_REPO_ROOT_DIR}/cgcs-root/build-tools/sign_rootfs-post-scripts
 # Definition for initramfs-sign-script, which is used to sign initramfs and mini initrd.
